//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.25 at 06:06:50 AM EEST 
//


package com.locations;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for footballTeams complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="footballTeams">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Attendance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Captain" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Stadium" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "footballTeams", propOrder = {
    "attendance",
    "captain",
    "country",
    "id",
    "name",
    "stadium"
})
public class FootballTeams {

    @XmlElement(name = "Attendance", required = true)
    protected String attendance;
    @XmlElement(name = "Captain", required = true)
    protected String captain;
    @XmlElement(name = "Country", required = true)
    protected String country;
    @XmlElement(name = "ID")
    protected int id;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Stadium", required = true)
    protected String stadium;

    /**
     * Gets the value of the attendance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttendance() {
        return attendance;
    }

    public FootballTeams(){}
	
    public FootballTeams(int id) {
	this.id = id;
    }
    public FootballTeams(String attendance, String captain, String country, int id, String name, String stadium) {
        this.attendance = attendance;
        this.captain = captain;
        this.country = country;
	this.id = id;
	this.name = name;
	this.stadium = stadium;
    }
    /**
     * Sets the value of the attendance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttendance(String value) {
        this.attendance = value;
    }

    /**
     * Gets the value of the captain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaptain() {
        return captain;
    }

    /**
     * Sets the value of the captain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaptain(String value) {
        this.captain = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public int getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setID(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the stadium property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public String getStadium() {
        return stadium;
    }

    /**
     * Sets the value of the stadium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStadium(String value) {
        this.stadium = value;
    }

}
