//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.25 at 06:06:50 AM EEST 
//


package com.locations;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.locations package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.locations
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllWeatherResponse }
     * 
     */
    public GetAllWeatherResponse createGetAllWeatherResponse() {
        return new GetAllWeatherResponse();
    }

    /**
     * Create an instance of {@link Weather }
     * 
     */
    public Weather createWeather() {
        return new Weather();
    }

    /**
     * Create an instance of {@link CreateWeatherResponse }
     * 
     */
    public CreateWeatherResponse createCreateWeatherResponse() {
        return new CreateWeatherResponse();
    }

    /**
     * Create an instance of {@link GetWeatherRequest }
     * 
     */
    public GetWeatherRequest createGetWeatherRequest() {
        return new GetWeatherRequest();
    }

    /**
     * Create an instance of {@link GetAllWeatherRequest }
     * 
     */
    public GetAllWeatherRequest createGetAllWeatherRequest() {
        return new GetAllWeatherRequest();
    }

    /**
     * Create an instance of {@link CreateWeatherRequest }
     * 
     */
    public CreateWeatherRequest createCreateWeatherRequest() {
        return new CreateWeatherRequest();
    }

    /**
     * Create an instance of {@link DeleteWeatherRequest }
     * 
     */
    public DeleteWeatherRequest createDeleteWeatherRequest() {
        return new DeleteWeatherRequest();
    }

    /**
     * Create an instance of {@link DeleteWeatherResponse }
     * 
     */
    public DeleteWeatherResponse createDeleteWeatherResponse() {
        return new DeleteWeatherResponse();
    }

    /**
     * Create an instance of {@link GetWeatherResponse }
     * 
     */
    public GetWeatherResponse createGetWeatherResponse() {
        return new GetWeatherResponse();
    }

    /**
     * Create an instance of {@link UpdateWeatherRequest }
     * 
     */
    public UpdateWeatherRequest createUpdateWeatherRequest() {
        return new UpdateWeatherRequest();
    }

    /**
     * Create an instance of {@link UpdateWeatherResponse }
     * 
     */
    public UpdateWeatherResponse createUpdateWeatherResponse() {
        return new UpdateWeatherResponse();
    }

    /**
     * Create an instance of {@link FootballTeams }
     * 
     */
    public FootballTeams createFootballTeams() {
        return new FootballTeams();
    }

}
